-- =========================================================================
-- SQL SCRIPT: Cấu hình Database cho Netflix Clone trên Supabase
-- Hãy sao chép toàn bộ mã SQL dưới đây và chạy trong mục "SQL Editor" của Supabase.
-- =========================================================================

-- 1. TẠO BẢNG HỒ SƠ NGƯỜI DÙNG (PROFILES)
-- Bảng này liên kết với bảng auth.users mặc định của Supabase
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TẠO BẢNG DANH SÁCH YÊU THÍCH (FAVORITES)
CREATE TABLE IF NOT EXISTS public.favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  movie_slug TEXT NOT NULL,      -- Slug của phim dùng để gọi OPhim API
  movie_name TEXT NOT NULL,      -- Tên hiển thị của phim
  movie_thumb TEXT,              -- Link ảnh thumbnail của phim
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Đảm bảo mỗi profile không thể thêm trùng lặp một bộ phim vào danh sách
  UNIQUE (profile_id, movie_slug)
);

-- 3. TẠO BẢNG LỊCH SỬ XEM PHIM (WATCH_HISTORY)
CREATE TABLE IF NOT EXISTS public.watch_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  movie_slug TEXT NOT NULL,      -- Slug phim từ OPhim API
  movie_name TEXT NOT NULL,      -- Tên phim
  episode_name TEXT NOT NULL,    -- Tên tập phim đang xem (Ví dụ: "Tập 1", "Full")
  duration_watched INTEGER DEFAULT 0 NOT NULL, -- Số giây đã xem (giây)
  total_duration INTEGER DEFAULT 0 NOT NULL,   -- Tổng số giây của video (giây)
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Đảm bảo lịch sử lưu vết theo từng phim cho mỗi profile
  UNIQUE (profile_id, movie_slug)
);

-- =========================================================================
-- 4. KÍCH HOẠT ROW LEVEL SECURITY (RLS) - BẢO MẬT DỮ LIỆU
-- =========================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watch_history ENABLE ROW LEVEL SECURITY;

-- =========================================================================
-- 5. ĐỊNH NGHĨA CÁC CHÍNH SÁCH BẢO MẬT (POLICIES)
-- =========================================================================

-- --- CHÍNH SÁCH CHO BẢNG PROFILES ---
-- Cho phép người dùng đọc hồ sơ của chính mình
CREATE POLICY "Users can view their own profiles" 
ON public.profiles FOR SELECT 
USING (auth.uid() = user_id);

-- Cho phép người dùng tự tạo hồ sơ cho mình
CREATE POLICY "Users can insert their own profiles" 
ON public.profiles FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Cho phép người dùng cập nhật hồ sơ của chính mình
CREATE POLICY "Users can update their own profiles" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = user_id);

-- Cho phép người dùng xóa hồ sơ của chính mình
CREATE POLICY "Users can delete their own profiles" 
ON public.profiles FOR DELETE 
USING (auth.uid() = user_id);


-- --- CHÍNH SÁCH CHO BẢNG FAVORITES ---
-- Cho phép người dùng đọc danh sách yêu thích thuộc về profile của mình
CREATE POLICY "Users can view their own favorites" 
ON public.favorites FOR SELECT 
USING (
  profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid())
);

-- Cho phép người dùng thêm phim vào danh sách yêu thích
CREATE POLICY "Users can insert their own favorites" 
ON public.favorites FOR INSERT 
WITH CHECK (
  profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid())
);

-- Cho phép người dùng xóa phim khỏi danh sách yêu thích
CREATE POLICY "Users can delete their own favorites" 
ON public.favorites FOR DELETE 
USING (
  profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid())
);


-- --- CHÍNH SÁCH CHO BẢNG WATCH_HISTORY ---
-- Cho phép người dùng xem lịch sử của chính mình
CREATE POLICY "Users can view their own watch history" 
ON public.watch_history FOR SELECT 
USING (
  profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid())
);

-- Cho phép thêm lịch sử xem mới
CREATE POLICY "Users can insert their own watch history" 
ON public.watch_history FOR INSERT 
WITH CHECK (
  profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid())
);

-- Cho phép cập nhật tiến độ xem phim (ví dụ cập nhật số giây đã xem)
CREATE POLICY "Users can update their own watch history" 
ON public.watch_history FOR UPDATE 
USING (
  profile_id IN (SELECT id FROM public.profiles WHERE user_id = auth.uid())
);


-- =========================================================================
-- 6. TỰ ĐỘNG TẠO 1 PROFILE MẶC ĐỊNH KHI CÓ USER MỚI ĐĂNG KÝ (TRIGGER)
-- =========================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (user_id, name, avatar_url)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', 'Mới gia nhập'), -- Tên từ social login hoặc mặc định
    'https://api.dicebear.com/7.x/bottts/svg?seed=' || new.id       -- Avatar mặc định ngẫu nhiên
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Kích hoạt trigger sau khi chèn user vào auth.users
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
