-- =========================================================================
-- SQL SCRIPT: Cấu hình pgvector cho Semantic Movie Search
-- Chạy toàn bộ script này trong Supabase SQL Editor.
-- =========================================================================

-- BƯỚC 1: Kích hoạt pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- =========================================================================
-- BƯỚC 2: Tạo bảng movies_cache để lưu metadata phim + vector embedding
-- (Dữ liệu phim được fetch từ OPhim API rồi cache lại tại đây)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.movies_cache (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug         TEXT UNIQUE NOT NULL,               -- Slug duy nhất từ OPhim API
  name         TEXT NOT NULL,                      -- Tên phim (Tiếng Việt)
  origin_name  TEXT,                               -- Tên gốc (Tiếng Anh / ngôn ngữ gốc)
  thumb_url    TEXT,                               -- Ảnh thumbnail
  description  TEXT,                               -- Mô tả / nội dung phim
  year         INT,                                -- Năm sản xuất
  category     JSONB,                              -- Thể loại (JSON array)
  country      JSONB,                              -- Quốc gia (JSON array)
  embedding    vector(3072),                       -- Gemini gemini-embedding-001 (3072 dims)
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
  updated_at   TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- =========================================================================
-- BƯỚC 3: Tạo chỉ mục HNSW để tìm kiếm vector nhanh (cosine distance)
-- =========================================================================
CREATE INDEX IF NOT EXISTS movies_cache_embedding_idx
  ON public.movies_cache
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- =========================================================================
-- BƯỚC 4: Tạo hàm match_movies dùng Cosine Similarity (<=>)
-- query_embedding : vector 768 chiều từ Gemini
-- match_threshold : ngưỡng tương đồng tối thiểu (vd: 0.5)
-- match_count     : số kết quả trả về tối đa
-- =========================================================================
CREATE OR REPLACE FUNCTION public.match_movies(
  query_embedding vector(3072),
  match_threshold float,
  match_count     int
)
RETURNS TABLE (
  id          bigint,
  slug        text,
  name        text,
  origin_name text,
  thumb_url   text,
  description text,
  year        int,
  category    jsonb,
  country     jsonb,
  similarity  float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    mc.id,
    mc.slug,
    mc.name,
    mc.origin_name,
    mc.thumb_url,
    mc.description,
    mc.year,
    mc.category,
    mc.country,
    1 - (mc.embedding <=> query_embedding) AS similarity
  FROM public.movies_cache mc
  WHERE mc.embedding IS NOT NULL
    AND 1 - (mc.embedding <=> query_embedding) > match_threshold
  ORDER BY mc.embedding <=> query_embedding
  LIMIT match_count;
$$;

-- =========================================================================
-- BƯỚC 5: Row Level Security cho movies_cache
-- Cho phép tất cả người dùng (authenticated + anon) đọc cache phim
-- Chỉ service_role mới được INSERT / UPDATE / DELETE
-- =========================================================================
ALTER TABLE public.movies_cache ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read movies_cache"
  ON public.movies_cache FOR SELECT
  USING (true);
